- name: Descarga media patrolagent
  get_url:
   url: http://{{ websrvsimple }}:{{ websrvport }}/Base_Linux_Patrol_Without.tar.gz
   dest: /tmp/Base_AIX_Patrol_Without.tar.gz
   owner: patrol
   group: grppatro
   mode: 0754
   force_basic_auth: yes
  when: ansible_facts['system'] == "AIX"

- name: Descarga media patrolagent
  get_url:
   url: http://{{ websrvsimple }}:{{ websrvport }}/Base_Linux_Patrol_Without.tar.gz
   dest: /tmp/Base_AIX_Patrol_Without.tar.gz
   owner: patrol
   group: grppatro
   mode: 0754
   force_basic_auth: yes
  when: ansible_facts['system'] == "Linux"

- name: Descarga media patrolagent
  get_url:
   url: http://{{ websrvsimple }}:{{ websrvport }}/Base_Solaris_Patrol_Without.tar.gz
   dest: /tmp/Base_AIX_Patrol_Without.tar.gz
   owner: patrol
   group: grppatro
   mode: 0754
   force_basic_auth: yes
  when: ansible_facts['system'] == "Solaris"
