---
- name: Descarga media PatrolAgent AIX en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  get_url:
   dest: /tmp/Base_AIX_Patrol_Without.tar.gz
   url: http://{{ websrvsimple }}:{{ websrvport }}/Base_Linux_Patrol_Without.tar.gz
   owner: patrol
   group: grppatro
   mode: 0754
   force_basic_auth: yes
  when: ansible_facts['system'] == "AIX"

- name: Descarga media PatrolAgent Linux en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  get_url:
   dest: /tmp/Base_Linux_Patrol_Without.tar.gz
   url: http://{{ websrvsimple }}:{{ websrvport }}/Base_Linux_Patrol_Without.tar.gz
   owner: patrol
   group: grppatro
   mode: 0754
   force_basic_auth: yes
  when: ansible_facts['system'] == "Linux"

- name: Descarga media PatrolAgent Solaris en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  get_url:   
   dest: /tmp/Base_Solaris_Patrol_Without.tar.gz
   url: http://{{ websrvsimple }}:{{ websrvport }}/Base_Solaris_Patrol_Without.tar.gz
   owner: patrol
   group: grppatro
   mode: 0754
   force_basic_auth: yes
  when: ansible_facts['system'] == "Solaris"
  
- name: Validar permisos en el directorio patrol en el remote host "{{ ansible_facts['nodename'] }}"
  stat:
   path: /patrol/
  register: siperejcdirpa
  
- name: Correccion de permisos al directorio /patrol antes de instalar en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  file:
    path: /patrol/
    state: directory
    owner: patrol
    group: grppatro
    mode: 0755
  when: siperejcdirpa.stat.mode != "0755"

- name: Cambiar permisos al Inslador PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  file:
    path: /tmp/Base_{{ ansible_facts['system'] }}_Patrol_Without.tar.gz
    owner: patrol
    group: grppatro
    mode: 0754

- name: Extraer el Inslador PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_user: patrol
  become_method: su
  become_exe: sudo su -
  unarchive:
    src: /tmp/Base_{{ ansible_system }}_Patrol_Without.tar.gz
    dest: /tmp
    mode: 0754
    remote_src: yes

- name: Obtener la version actual PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_user: patrol
  become_method: su
  become_exe: sudo su -
  shell: /patrol/Patrol3/PatrolAgent -v > ~/out_PatrolAgentVersion 2> ~/val_PatrolAgentVersion
  ignore_errors: yes

- name: Obtener la version actual PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_user: patrol
  become_method: su
  become_exe: sudo su -
  shell: cat val_PatrolAgentVersion out_PatrolAgentVersion
  register: valpaver

- name: Iniciar la instalacion de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_user: patrol
  become_method: su
  become_exe: sudo su -
  shell: |
    cd /tmp/bmc_products/
    ./RunSilentInstall.sh -no_backup
  when: valpaver.stdout.split()[1] != "V22.1.00i"

- name: Baja y reconfiguracion el servicios de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_user: patrol
  become_method: su
  become_exe: sudo su -
  shell: /patrol/Patrol3/scripts.d/S50PatrolAgent.sh stop
  when: valpaver.stdout.split()[1] != "V22.1.00i"
