---
- name: Descarga media PatrolAgent AIX en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  get_url:
   dest: /tmp/Base_{{ ansible_facts['system'] }}_Patrol_Without.tar.gz
   url: http://{{ websrvsimple }}:{{ websrvport }}/Base_{{ ansible_facts['system'] }}_Patrol_Without.tar.gz
   owner: patrol
   group: grppatro
   mode: 0754
   force_basic_auth: yes
  when: ansible_facts['system'] == "AIX"

- name: Descarga media PatrolAgent Linux en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  get_url:
   dest: /tmp/Base_{{ ansible_facts['system'] }}_Patrol_Without.tar.gz
   url: http://{{ websrvsimple }}:{{ websrvport }}/Base_{{ ansible_facts['system'] }}_Patrol_Without.tar.gz
   owner: patrol
   group: grppatro
   mode: 0754
   force_basic_auth: yes
  when: ansible_facts['system'] == "Linux"

- name: Descarga media PatrolAgent Solaris en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  get_url:   
   dest: /tmp/Base_{{ ansible_facts['system'] }}_Patrol_Without.tar.gz
   url: http://{{ websrvsimple }}:{{ websrvport }}/Base_{{ ansible_facts['system'] }}_Patrol_Without.tar.gz
   owner: patrol
   group: grppatro
   mode: 0754
   force_basic_auth: yes
  when: ansible_facts['system'] == "SunOS"
  
- name: Validar permisos en el directorio patrol en el remote host "{{ ansible_facts['nodename'] }}"
  stat:
   path: /patrol/
  register: siperejcdirpa
  
- name: Correccion de permisos al directorio /patrol antes de instalar en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  file:
    path: /patrol/
    state: directory
    owner: patrol
    group: grppatro
    mode: 0755
  when: siperejcdirpa.stat.mode != "0755"

- name: Extraer el Inslador PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  #become_user: patrol
  become_method: sudo
  #become_exe: sudo su -
  unarchive:
    src: /tmp/Base_{{ ansible_facts['system'] }}_Patrol_Without.tar.gz
    dest: /tmp
    mode: 0754
    remote_src: yes

- name: Cambiar permisos al Inslador PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  file:
    path: /tmp/bmc_products
    state: directory
    recurse: yes
    owner: patrol
    group: grppatro
    mode: 0754

- name: Generar salida de la version actual de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  #become_user: patrol
  become_method: sudo
  #become_exe: sudo su -
  shell: /patrol/Patrol3/PatrolAgent -v > /tmp/out_PatrolAgentVersion 2> /tmp/val_PatrolAgentVersion
  ignore_errors: yes

- name: Validar la version actual PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  #become_user: patrol
  become_method: sudo
  #become_exe: sudo su -
  shell: cat /tmp/out_PatrolAgentVersion /tmp/val_PatrolAgentVersion
  register: valpaver

- name: Iniciar la instalacion de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_user: patrol
  become_method: su
  become_exe: sudo su -
  shell: |
    cd /tmp/bmc_products/
    ./RunSilentInstall.sh -no_backup
  when: valpaver.stdout.split()[1] != "V22.1.00i"

- name: Generar salida de la version actual de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  #become_user: patrol
  become_method: sudo
  #become_exe: sudo su -
  shell: /patrol/Patrol3/PatrolAgent -v > /tmp/out_PatrolAgentVersion 2> /tmp/val_PatrolAgentVersion
  ignore_errors: yes

- name: Validar la version actual PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  #become_user: patrol
  become_method: sudo
  #become_exe: sudo su -
  shell: cat /tmp/out_PatrolAgentVersion /tmp/val_PatrolAgentVersion
  register: valpaver

- name: Validar el proceso de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  shell: ps -eo args | grep -v grep | grep -i patrolagent >/dev/null && echo ACTIVO || echo INACTIVO
  register: valpaproc

- name: Baja antes de la reconfiguracion el servicios de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_user: patrol
  become_method: su
  become_exe: sudo su -
  shell: /patrol/Patrol3/scripts.d/S50PatrolAgent.sh stop
  when:
    - valpaver.stdout.split()[1] == "V22.1.00i"
    - valpaproc.stdout == "ACTIVO"

- name: Validar el proceso de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  shell: ps -eo args | grep -v grep | grep -i patrolagent >/dev/null && echo ACTIVO || echo INACTIVO
  register: valpaproc

- name: Borrar directorios history y streamcache de PatrolAgent en el remote Host  "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /patrol/Patrol3/log/history/
    - /patrol/Patrol3/log/streamcache/
  when:
    - valpaver.stdout.split()[1] == "V22.1.00i"
    - valpaproc.stdout == "INACTIVO"
  
- name: Cambiar permisos directrio config_v3.X de PatrolAgent para reconfiguracion en el remote Host  "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  file:
    path: /patrol/common/security/config_v3.0/
    mode: 0744
  when:
    - valpaver.stdout.split()[1] == "V22.1.00i"
    - valpaproc.stdout == "INACTIVO"
    
- name: Ejecutar reconfiguracion PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  shell: |
      cd /patrol/Patrol3
      ./agent_configure.sh -d
      cd /patrol/common/security/config_v3.0
      ./sec_configure.sh /patrol/Patrol3 0
  when:
    - valpaver.stdout.split()[1] == "V22.1.00i"
    - valpaproc.stdout == "INACTIVO"
    
- name: Restaurar permisos directrio config_v3.X de PatrolAgent para reconfiguracion en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  file:
    path: /patrol/common/security/config_v3.0/
    mode: 0700
  when:
    - valpaver.stdout.split()[1] == "V22.1.00i"
    - valpaproc.stdout == "INACTIVO"

- name: Cambiar permisos a los archivos patrol.conf y dlls.conf de PatrolAgent en el remote Host Ansible "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  file:
    path: "{{ item }}"
    mode: 0644
  ignore_errors: yes
  with_items:
    - /etc/patrol.d/patrol.conf
    - /etc/patrol.d/dlls.conf
  when: 
    - valpaver.stdout.split()[1] == "V22.1.00i"
    - valpaproc.stdout == "INACTIVO"

- name: Cambiar permisos a los archivos patrol.conf y dlls.conf de PatrolAgent en el remote Host Ansible "{{ ansible_facts['nodename'] }}"
  become: yes
  become_method: sudo
  file:
    path: /etc/patrol.d/security_policy_v3.0
    state: directory
    recurse: yes
    mode: 0644
  when: 
    - valpaver.stdout.split()[1] == "V22.1.00i"
    - valpaproc.stdout == "INACTIVO"

- name: Alta despues de la reconfiguracion el servicios de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  become: yes
  become_user: patrol
  become_method: su
  become_exe: sudo su -
  shell: /patrol/Patrol3/scripts.d/S50PatrolAgent.sh start
  register: sttpaarc
  when: 
    - valpaver.stdout.split()[1] == "V22.1.00i"
    - valpaproc.stdout == "INACTIVO"

- name: Validar el proceso de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  shell: ps -eo args | grep -v grep | grep -i patrolagent >/dev/null && echo ACTIVO || echo INACTIVO
  register: valpaproc

- name: Resultado de la alta correcta de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  debug:
    msg:
     - "PatrolAgent ........ACTIVO"
     - "PatrolAgentVersion..{{ valpaver.stdout.split()[1] }}"
  when: valpaproc.stdout == "ACTIVO"

- name: Resultado de la alta incorrecta de PatrolAgent en el remote Host "{{ ansible_facts['nodename'] }}"
  fail:
    msg:
     - "PatrolAgent ........INACTIVO"
     - "PatrolAgentVersion..{{ valpaver.stdout.split()[1] }}"
     - "El procesos no pudo ser ACTIVADO correctamente"
     - "Favor de contactar al Area de RTMonitoring & Monitoring"
  when: valpaproc.stdout == "INACTIVO"

- name: Borrar medias Patrol del directorio Temporal
  become: yes
  become_method: sudo
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/bmc_products/
    - /tmp/Base_{{ ansible_facts['system'] }}_Patrol_Without.tar.gz
    - /tmp/out_PatrolAgentVersion
    - /tmp/val_PatrolAgentVersion
