---  
- name: Validar permisos en el directorio patrol en el remote host
  stat:
   path: /patrol/
  register: siperejcdirpa
  
- name: Correccion de permisos al directorio /patrol antes de instalar en el remote Host
  become: yes
  become_method: sudo
  file:
    path: /patrol/
    state: directory
    owner: patrol
    group: grppatro
    mode: 0755
  when: siperejcdirpa.stat.mode != "0755"

- name: Cambiar permisos al Inslador PatrolAgent en el remote Host
  become: yes
  become_method: sudo
  file:
    path: /tmp/Base_{{ ansible_facts['system'] }}_Patrol_Without.tar.gz
    owner: patrol
    group: grppatro
    mode: 0754
