---
- name: Ansible PlayBook - Borrar directorios Ansible
  #hosts: asitsmaop2.bvm.ibmes.bluecare.ibm.com
  hosts: asitsmaop2.awx.lab.net
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
   - name: Ansible delete file glob
     find:
       paths: /tmp/
       patterns: ansible_command_*
    register: deldirasb
