- name: Ansible PlayBook - Iniciar HTTP Simple
  #hosts: asitsmaop2.bvm.ibmes.bluecare.ibm.com
  hosts: asitsmaop2.awx.lab.net
  become: yes
  become_method: sudo

  tasks:
   - name: Mover medias al directorio temporal
     file:
      path: /tmp/pamediadwn
      state: directory
      owner: patrol
      group: grppatro
      mode: 0755

  tasks:
   - name: Mover medias al directorio temporal
     copy:
      src: /bmc/bmcinstallers/{{ item }}
      dest: /tmp/pamediadwn/
      owner: patrol
      group: grppatro
    with_items:
      - Base_AIX_Patrol_Without.tar.gz
      - Base_Linux_Patrol_Without.tar.gz
      - Base_Solaris_Patrol_Without.tar.gz

#  tasks:
#   - name: Inicair Simple HTTTP Server Python
#     shell: |
#        cd /tmp/
#        if [ "$(ps -eo args | grep SimpleHTTPServer | grep -v grep | tr -d " ")" = ""  ]
#        then
#        nohup python -m SimpleHTTPServer 8887 &
#        else
#        echo "python-mSimpleHTTPServer8887 iniciado"
#        fi
#        sleep 60
#     async: 900
#     poll: 0
