---
- name: Ansible PlayBook - Iniciar HTTP Simple
  #hosts: asitsmaop2.bvm.ibmes.bluecare.ibm.com
  hosts: asitsmaop2.awx.lab.net
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
   - name: Validar si existe diretorio temporal para medias de instalacion PatrolAgent
     stat:
       path: /tmp/pamediadwn/
     register: vdtmipa
 
  tasks:
   - name: Crear directorio temporal para medias de instalacion PatrolAgent
     file:
       path: /tmp/pamediadwn/
       state: directory
       owner: patrol
       group: grppatro
       mode: 0755
     when: vdtmipa.stat.exists

  tasks:
   - name: Mover medias de instalacion PatrolAgent al directorio temporal
     copy:
       src: /bmc/bmcinstallers/{{ item }}
       dest: /tmp/pamediadwn/
       owner: patrol
       group: grppatro
       remote_src: yes
     with_items:
       - Base_AIX_Patrol_Without.tar.gz
       - Base_Linux_Patrol_Without.tar.gz
       - Base_Solaris_Patrol_Without.tar.gz
     when: vdtmipa.stat.exists

  tasks:
   - name: Inicair Simple HTTTP Server Python
     shell: |
        cd /tmp/pamediadwn/
        if [ "$(ps -eo args | grep SimpleHTTPServer | grep -v grep | tr -d " ")" = ""  ]
        then
        nohup python -m SimpleHTTPServer 8887 &
        id
        else
        echo "python-mSimpleHTTPServer8887 iniciado"
        fi
        sleep 60
     async: 900
     poll: 0
