---
- name: Ansible PlayBook - Instalacion y Actualizacion PatrolAgent
  #hosts: asitsmaop2.bvm.ibmes.bluecare.ibm.com
  hosts: asitsmaop2.awx.lab.net
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
    - name: Validar si existe diretorio temporal para medias de instalacion PatrolAgent
      stat:
      path: /tmp/pamediadwn/
      register: siexdirtmp
   
