---
- name: Ansible PlayBook - Instalacion y Actualizacion PatrolAgent
  #hosts: asitsmaop2.bvm.ibmes.bluecare.ibm.com
  hosts: asitsmaop2.awx.lab.net
  gather_facts: yes
  become: yes
  become_method: sudo
  
  tasks:
   - name: Validar si existe diretorio temporal para medias de instalacion PatrolAgent
     stat:
      path: /tmp/pamediadwn/
     register: siexdirtmp

   - name: Crear directorio temporal para medias de instalacion PatrolAgent
     file:
      path: /tmp/pamediadwn/
      state: directory
      owner: patrol
      group: grppatro
      mode: 0755
     when: siexdirtmp.stat.exists == false

   - name: Validar el tamaño de directorio temporal para medias de instalacion PatrlAgent
     shell: du /tmp/pamediadwn/ | awk '{print $i/1024}' | cut -d . -f1
     register: sitoes

   - name: Mover medias de instalacion PatrolAgent al directorio temporal
     copy:
      src: /bmc/bmcinstallers/{{ item }}
      dest: /tmp/pamediadwn/
      owner: patrol
      group: grppatro
      remote_src: yes
     with_items:
       - Base_AIX_Patrol_Without.tar.gz
       - Base_Linux_Patrol_Without.tar.gz
       - Base_Solaris_Patrol_Without.tar.gz
     when: (siexdirtmp.stat.exists == true and sitoes.stdout >= 1016)
